python post_proc.py --entriesToRun 100 --inputFile /eos/cms/store/group/phys_b2g/zhenxuan/custom_nanoAOD/YH_beforeSKIM/UL2018_ttgg_signal/UL2018/GluGluToRadionToHHTo2G2Tau_M-1000/GluGluToRadionToHHTo2G2Tau_M-1000_6266116_15_CAD7E318CE0B.root -m True -y 2018
python post_proc.py --entriesToRun 100 --inputFile root://cms-xrd-global.cern.ch//store/group/phys_b2g/jodervan/nanoAOD_Mar24/UL2016/UL2016/GluGluToRadionToHHTo2G2WTo2G2Q1L1Nu_M-1500/C696ABB5-8D7D-3742-8BF9-0BD553D38059.root  -m True -y 2016post

python condor_setup_lxplus.py  --input_file sample_list_v9_2018FH.dat --eos_output_path /eos/cms/store/group/phys_b2g/shsong/nanoAODnTuples/nanoAODsys_Mar2024/UL2018_HHsignal/ --use_custom_eos --submission_name Run2018_FH --year 2018 --isMC --DontCreateTarFile
python condor_setup_lxplus.py  --input_file sample_list_v9_2018SL.dat --eos_output_path /eos/cms/store/group/phys_b2g/shsong/nanoAODnTuples/nanoAODsys_Mar2024/UL2018_HHsignal/ --use_custom_eos --submission_name Run2018_SL --year 2018 --isMC --DontCreateTarFile
python condor_setup_lxplus.py  --input_file sample_list_v9_2018bbgg.dat --eos_output_path /eos/cms/store/group/phys_b2g/shsong/nanoAODnTuples/nanoAODsys_Mar2024/UL2018_HHsignal/ --use_custom_eos --submission_name Run2018_bbgg --year 2018 --isMC --DontCreateTarFile
python condor_setup_lxplus.py  --input_file sample_list_v9_2017signal.dat --eos_output_path /eos/cms/store/group/phys_b2g/shsong/nanoAODnTuples/nanoAODsys_Mar2024/UL2017_HHsignal/ --use_custom_eos --submission_name Run2017 --year 2017 --isMC --DontCreateTarFile

python condor_setup_lxplus.py  --input_file sample_list_UL2016APV_wwggFHSL_bbgg_zzgg.dat --eos_output_path /eos/cms/store/group/phys_b2g/shsong/nanoAODnTuples/nanoAODsys_Mar2024/UL2016pre_HHsignal/ --use_custom_eos --submission_name UL2016APV_wwggFHSL_bbgg_zzgg --year 2016pre --isMC --DontCreateTarFile
python condor_setup_lxplus.py  --input_file sample_list_UL2016APV_bbgg.dat --eos_output_path /eos/cms/store/group/phys_b2g/shsong/nanoAODnTuples/nanoAODsys_Mar2024/UL2016pre_bbgg/ --use_custom_eos --submission_name UL2016APV_bbgg --year 2016pre --isMC --DontCreateTarFile
python condor_setup_lxplus.py  --input_file sample_list_UL2016_preVFP_ttgg.dat --eos_output_path /eos/cms/store/group/phys_b2g/shsong/nanoAODnTuples/nanoAODsys_Mar2024/UL2016pre_ttgg/ --use_custom_eos --submission_name UL2016APV_ttgg --year 2016pre --isMC --DontCreateTarFile
python condor_setup_lxplus.py  --input_file sample_list_UL2016_wwggFHSL_bbgg_zzgg_ttgg.dat --eos_output_path /eos/cms/store/group/phys_b2g/shsong/nanoAODnTuples/nanoAODsys_Mar2024/UL2016post_HHsignal/ --use_custom_eos --submission_name UL2016_wwggFHSL_bbgg_zzgg_ttgg --year 2016post --isMC --DontCreateTarFile
python condor_setup_lxplus.py  --input_file sample_list_UL2016_signleHiggs.dat --eos_output_path /eos/cms/store/group/phys_b2g/shsong/nanoAODnTuples/nanoAODsys_Mar2024/UL2016post_SingleH/ --use_custom_eos --submission_name UL2016_SingleH --year 2016post --isMC  --DontCreateTarFile

